'use client'

import { useEffect, useMemo, useState } from 'react'
import { Heart, MapPin, Search, SlidersHorizontal, Bug, ChevronRight, Navigation, X, LocateFixed, RefreshCw, Copy, Clock3, Store, LayoutList, Map as MapIcon, Settings2 } from 'lucide-react'

type Bucket = 'IN_STOCK' | 'CONFIRM_WITH_STORE' | 'OUT_OF_STOCK' | 'UNKNOWN'
type StoreItem = { id: string; name: string; distance: number; price: number; bucket: Bucket; address: string; lat: number; lng: number }
type Product = { id: string; name: string; brand: string; category: string; color: string; stores: StoreItem[] }

const cities = [{name:'Dhanbad',lat:23.7957,lng:86.4304},{name:'Ranchi',lat:23.3441,lng:85.3096},{name:'Kolkata',lat:22.5726,lng:88.3639},{name:'Delhi',lat:28.6139,lng:77.209},{name:'Mumbai',lat:19.076,lng:72.8777},{name:'Bengaluru',lat:12.9716,lng:77.5946}]
const seedProducts: Product[] = [
 {id:'coke-500',name:'Coca-Cola 500ml',brand:'Coca-Cola',category:'Soft drinks',color:'#fef0ee',stores:[{id:'vijay',name:'Vijay Sales',distance:2.1,price:40,bucket:'IN_STOCK',address:'Bank More, Dhanbad',lat:23.79,lng:86.43},{id:'daily',name:'Daily Needs Market',distance:3.4,price:42,bucket:'CONFIRM_WITH_STORE',address:'Saraidhela, Dhanbad',lat:23.81,lng:86.45},{id:'fresh',name:'Fresh Basket',distance:4.5,price:39,bucket:'OUT_OF_STOCK',address:'Hirapur, Dhanbad',lat:23.78,lng:86.41}]},
 {id:'lays-classic',name:'Lay\'s Classic Salted',brand:'Lay\'s',category:'Snacks',color:'#fff7db',stores:[{id:'city',name:'City Supermart',distance:1.4,price:30,bucket:'IN_STOCK',address:'Main Road, Dhanbad',lat:23.8,lng:86.42},{id:'vijay',name:'Vijay Sales',distance:2.1,price:32,bucket:'CONFIRM_WITH_STORE',address:'Bank More, Dhanbad',lat:23.79,lng:86.43}]},
 {id:'amul-milk',name:'Amul Taaza Milk 1L',brand:'Amul',category:'Dairy',color:'#eaf5ff',stores:[{id:'fresh',name:'Fresh Basket',distance:4.5,price:58,bucket:'IN_STOCK',address:'Hirapur, Dhanbad',lat:23.78,lng:86.41},{id:'daily',name:'Daily Needs Market',distance:3.4,price:60,bucket:'CONFIRM_WITH_STORE',address:'Saraidhela, Dhanbad',lat:23.81,lng:86.45}]},
]
const bucketLabel = (b:Bucket) => b==='IN_STOCK'?'In stock':b==='CONFIRM_WITH_STORE'?'Confirm with store':b==='OUT_OF_STOCK'?'Out of stock':'Unknown'
const bucketClass = (b:Bucket) => b==='IN_STOCK'?'good':b==='CONFIRM_WITH_STORE'?'warn':'bad'

export default function Page(){
 const [location,setLocation]=useState(cities[0]); const [radius,setRadius]=useState(5); const [locationOpen,setLocationOpen]=useState(false); const [query,setQuery]=useState(''); const [debounced,setDebounced]=useState(''); const [view,setView]=useState<'list'|'map'>('list'); const [tab,setTab]=useState<'search'|'favourites'>('search'); const [sort,setSort]=useState('nearest'); const [hideOut,setHideOut]=useState(true); const [debug,setDebug]=useState(false); const [drawer,setDrawer]=useState(false); const [selected,setSelected]=useState<{product:Product;store:StoreItem}|null>(null); const [favs,setFavs]=useState<string[]>([]); const [tick,setTick]=useState(0); const [lastChange,setLastChange]=useState(new Date());
 useEffect(()=>{const raw=localStorage.getItem('findme-favs'); if(raw) setFavs(JSON.parse(raw))},[])
 useEffect(()=>{localStorage.setItem('findme-favs',JSON.stringify(favs))},[favs])
 useEffect(()=>{const id=setTimeout(()=>setDebounced(query),300);return()=>clearTimeout(id)},[query])
 useEffect(()=>{const id=setInterval(()=>{setTick(v=>v+1);setLastChange(new Date())},15000);return()=>clearInterval(id)},[])
 const products=useMemo(()=>{let data=seedProducts.map(p=>({...p,stores:p.stores.map(s=>({...s,bucket:(tick>0&&s.id==='daily'&&p.id==='coke-500'&&tick%2===1)?'IN_STOCK':s.bucket}))})); if(debounced.length<2)return []; const normalizedQuery=debounced.toLowerCase().replace('coke','coca-cola'); const filtered=data.filter(p=>(p.name+' '+p.brand+' '+p.category).toLowerCase().includes(normalizedQuery)); return filtered.map(p=>({...p,stores:[...p.stores].filter(s=>!hideOut||s.bucket!=='OUT_OF_STOCK').sort((a,b)=>sort==='cheapest'?a.price-b.price:sort==='availability'? (a.bucket==='IN_STOCK'?-1:1)-(b.bucket==='IN_STOCK'?-1:1):a.distance-b.distance)}))},[debounced,hideOut,sort,tick])
 const toggleFav=(id:string)=>setFavs(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id])
 const openProduct=(p:Product,s:StoreItem)=>setSelected({product:p,store:s})
 const results=tab==='favourites'?seedProducts.filter(p=>favs.includes(p.id)||p.stores.some(s=>favs.includes(s.id))):products
 return <div className="app-shell">
  <header className="topbar"><div className="brand"><div className="brand-mark">FM</div><div><strong>Find Me</strong><span>Customer test harness</span></div></div><div className="top-actions"><button className={'debug-toggle '+(debug?'active':'')} onClick={()=>{setDebug(!debug);setDrawer(debug)}} aria-label="Toggle debug"><Bug size={16}/><span className="hide-mobile">Debug</span></button><button className="icon-btn" onClick={()=>setLocationOpen(true)} aria-label="Set location"><Settings2 size={18}/></button></div></header>
  {debug&&<div className="debug-banner"><Bug size={14}/> DEBUG MODE · exact quantities are shown for testing only</div>}
  <main><section className="hero"><div><p className="eyebrow">NEARBY MARKETPLACE</p><h1>Find it near you.</h1><p className="subhead">Search local stores before you make the trip.</p></div><button className="location-chip" onClick={()=>setLocationOpen(true)}><MapPin size={16}/><span>{location.name}</span><small>{radius} km</small></button></section>
   <div className="search-wrap"><Search size={20}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search products, brands, categories" aria-label="Search products"/><kbd>⌘ K</kbd>{query&&<button className="clear" onClick={()=>setQuery('')}><X size={16}/></button>}</div>
   {!query&&<div className="quick-row"><span>Try searching</span>{['Chips','Coke','Milk','Headphones','Rice'].map(x=><button key={x} onClick={()=>setQuery(x)}>{x}</button>)}</div>}
   <div className="toolbar"><div className="tabs"><button className={tab==='search'?'selected':''} onClick={()=>setTab('search')}>Search</button><button className={tab==='favourites'?'selected':''} onClick={()=>setTab('favourites')}><Heart size={15}/> Favourites <em>{favs.length}</em></button></div><div className="view-toggle"><button className={view==='list'?'selected':''} onClick={()=>setView('list')}><LayoutList size={15}/> List</button><button className={view==='map'?'selected':''} onClick={()=>setView('map')}><MapIcon size={15}/> Map</button></div></div>
   {query.length<2&&tab==='search'?<div className="empty-state"><div className="empty-icon"><Search size={24}/></div><h2>What are you looking for?</h2><p>Set your location, then search across nearby stores.</p><button onClick={()=>setLocationOpen(true)} className="primary-btn"><LocateFixed size={16}/> Set location</button></div>:view==='map'?<MapView products={results} onSelect={openProduct}/>:<section className="results"><div className="result-header"><div><strong>{results.length} product matches</strong><span> · within {radius} km of {location.name}</span></div><div className="filters"><select value={sort} onChange={e=>setSort(e.target.value)} aria-label="Sort results"><option value="nearest">Nearest</option><option value="cheapest">Cheapest</option><option value="availability">Availability</option></select><label><input type="checkbox" checked={hideOut} onChange={e=>setHideOut(e.target.checked)}/> Hide out of stock</label></div></div>{results.length===0?<div className="empty-state compact"><h2>No stores near you have this</h2><p>Try another product or expand your search radius.</p></div>:results.map(p=><ProductCard key={p.id} product={p} favs={favs} onFav={toggleFav} onSelect={openProduct} debug={debug}/>)}</section>}
  </main>
  <button className="floating-debug" onClick={()=>setDrawer(true)}><Bug size={18}/>{debug?'Debug log':'Debug'}</button>
  {locationOpen&&<LocationSheet current={location} radius={radius} onClose={()=>setLocationOpen(false)} onCity={c=>{setLocation(c);setLocationOpen(false)}} onRadius={setRadius}/>} 
  {selected&&<ProductSheet product={selected.product} store={selected.store} favs={favs} onFav={toggleFav} onClose={()=>setSelected(null)} debug={debug} lastChange={lastChange}/>} 
  {drawer&&<DebugDrawer onClose={()=>setDrawer(false)} onRefetch={()=>setTick(v=>v+1)}/>} 
 </div>
}

function ProductCard({product,favs,onFav,onSelect,debug}:{product:Product;favs:string[];onFav:(id:string)=>void;onSelect:(p:Product,s:StoreItem)=>void;debug:boolean}){return <article className="product-card"><div className="product-head"><div className="product-art" style={{background:product.color}}><Store size={22}/></div><div className="product-title"><span>{product.brand}</span><h2>{product.name}</h2><small>{product.category} · {product.stores.length} nearby stores</small></div><button className={'heart '+(favs.includes(product.id)?'liked':'')} onClick={()=>onFav(product.id)} aria-label="Favourite product"><Heart size={18} fill={favs.includes(product.id)?'currentColor':'none'}/></button></div><div className="store-list">{product.stores.map(s=><button className={'store-row '+(s.bucket==='OUT_OF_STOCK'?'dim':'')} key={s.id+s.name} onClick={()=>onSelect(product,s)}><span className="store-name"><Store size={14}/>{s.name}{favs.includes(s.id)&&<Heart size={12} fill="currentColor"/>}</span><span>{s.distance.toFixed(1)} km</span><strong>Rs {s.price}</strong><span className={'status '+bucketClass(s.bucket)}>{bucketLabel(s.bucket)}</span><ChevronRight size={16}/>{debug&&<small className="debug-line">bucket={s.bucket} · qty=** · searchable=true</small>}</button>)}</div></article>}
function MapView({products,onSelect}:{products:Product[];onSelect:(p:Product,s:StoreItem)=>void}){return <div className="map-panel"><div className="map-grid"></div><div className="map-label">OpenStreetMap preview</div>{products.flatMap(p=>p.stores).map((s,i)=><button key={s.id+i} className={'map-pin '+bucketClass(s.bucket)} style={{left:(18+i*19)%82+'%',top:(25+i*13)%60+'%'}} onClick={()=>onSelect(products[i%products.length],s)}><MapPin size={25} fill="currentColor"/></button>)}<div className="map-card"><span className="status good">{products.length} products</span><strong>Stores around you</strong><small>Tap a pin to inspect availability</small></div></div>}
function LocationSheet({current,radius,onClose,onCity,onRadius}:{current:typeof cities[0];radius:number;onClose:()=>void;onCity:(c:typeof cities[0])=>void;onRadius:(r:number)=>void}){return <div className="overlay"><div className="sheet"><div className="sheet-handle"/><div className="sheet-title"><div><p className="eyebrow">YOUR SEARCH AREA</p><h2>Location & radius</h2></div><button className="icon-btn" onClick={onClose}><X size={18}/></button></div><button className="current-location" onClick={()=>onCity(cities[0])}><LocateFixed size={18}/><div><strong>Use my current location</strong><small>Allow browser location access</small></div><ChevronRight size={17}/></button><p className="section-label">Preset cities</p><div className="city-grid">{cities.map(c=><button className={current.name===c.name?'active':''} key={c.name} onClick={()=>onCity(c)}>{c.name}</button>)}</div><p className="section-label">Search radius</p><div className="radius-row">{[1,3,5,10,20].map(r=><button className={radius===r?'active':''} key={r} onClick={()=>onRadius(r)}>{r} km</button>)}</div><button className="primary-btn full" onClick={onClose}>Apply location</button></div></div>}
function ProductSheet({product,store,favs,onFav,onClose,debug,lastChange}:{product:Product;store:StoreItem;favs:string[];onFav:(id:string)=>void;onClose:()=>void;debug:boolean;lastChange:Date}){const [bucket,setBucket]=useState(store.bucket);useEffect(()=>{const id=setInterval(()=>setBucket(v=>v==='IN_STOCK'?'CONFIRM_WITH_STORE':'IN_STOCK'),5000);return()=>clearInterval(id)},[]);return <div className="overlay"><div className="sheet detail-sheet"><div className="sheet-handle"/><div className="sheet-title"><div><p className="eyebrow">LIVE PRODUCT VIEW</p><h2>{product.name}</h2><small>{store.name} · {store.address}</small></div><button className="icon-btn" onClick={onClose}><X size={18}/></button></div><div className="detail-price"><span>Current price</span><strong>Rs {store.price}</strong><button className={'heart '+(favs.includes(product.id)?'liked':'')} onClick={()=>onFav(product.id)}><Heart size={19} fill={favs.includes(product.id)?'currentColor':'none'}/></button></div><div className={'availability '+bucketClass(bucket)}><div><small>AVAILABILITY</small><strong>{bucketLabel(bucket)}</strong></div><span className="pulse-dot"/></div><div className="updated"><Clock3 size={14}/> Last updated just now · auto-refreshing every 5s</div>{debug&&<div className="debug-box"><strong>Debug payload</strong><code>availability_bucket: {bucket}<br/>available_qty: **<br/>version: v_{Math.floor(lastChange.getTime()/1000)}<br/>searchable: true</code></div>}<button className="reserve" disabled>Reserve <small>Reservation arrives in Phase 4</small></button></div></div>}
function DebugDrawer({onClose,onRefetch}:{onClose:()=>void;onRefetch:()=>void}){return <div className="drawer-overlay" onClick={onClose}><aside className="debug-drawer" onClick={e=>e.stopPropagation()}><div className="sheet-title"><div><p className="eyebrow">OBSERVABILITY</p><h2>Debug panel</h2></div><button className="icon-btn" onClick={onClose}><X size={18}/></button></div><div className="debug-box"><strong>Last stock change</strong><p>Seen 5.0 seconds after previous poll</p><small>Polling paused while tab is hidden.</small></div><p className="section-label">Recent API calls</p>{['GET /api/marketplace/search · 200 · 86ms','GET /stores/vijay/products · 200 · 112ms','GET /availability/coke-500 · 200 · 74ms'].map(x=><div className="api-row" key={x}><code>{x}</code></div>)}<div className="drawer-actions"><button onClick={onRefetch}><RefreshCw size={15}/> Force refetch</button><button onClick={()=>navigator.clipboard?.writeText('curl -H "X-Debug: 1" /api/marketplace/search')}><Copy size={15}/> Copy request as curl</button></div></aside></div>}
